export ZSH=~/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# use vi mode by default
bindkey -v

# show indicator to see which mode we are in
function zle-line-init zle-keymap-select {
    RPS1="${${KEYMAP/vicmd/-- NORMAL --}/(main|viins)/-- INSERT --}"
    RPS2=$RPS1
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

# kill the lag when switching mode
export KEYTIMEOUT=1
# cycle through historis in insert mode
bindkey -M viins '^R' history-incremental-pattern-search-backward
bindkey -M viins '^F' history-incremental-pattern-search-forward
