export ZSH=~/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(
  git
)

[ -s "$ZSH/oh-my-zsh.sh" ] && source $ZSH/oh-my-zsh.sh

# use vi mode by default
bindkey -v

# show indicator to see which mode we are in
function zle-line-init zle-keymap-select {
    RPS1="${${KEYMAP/vicmd/-- NORMAL --}/(main|viins)/-- INSERT --}"
    RPS2=$RPS1
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

# kill the lag when switching mode
export KEYTIMEOUT=1
# cycle through historis in insert mode
bindkey -M viins '^R' history-incremental-pattern-search-backward
bindkey -M viins '^F' history-incremental-pattern-search-forward

export XDG_CONFIG_HOME=~/.config
export NVM_DIR=$XDG_CONFIG_HOME/nvm


alias tmux='TERM=xterm-256color tmux -f "$XDG_CONFIG_HOME"/tmux/tmux.conf'
alias vim="nvim"


# for flutter
export PATH="$PATH:$XDG_CONFIG_HOME/framework/flutter/bin":"$HOME/.pub-cache/bin"
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn


export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

#ruby config
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export HOMEBREW_NO_CLEANUP_FORMULAE="nvim"

export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

# Created by `pipx` on 2022-02-03 09:25:05
export PATH="$PATH:$HOME/.local/bin"

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end
export PATH="/opt/homebrew/opt/python@3.10/bin:$PATH"

export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
