#!/usr/bin/env bash
#
# binance-cli.sh — recreate the tmuxinator `binance-cli` project inside Herdr.
#
# Source of truth: ~/.config/tmuxinator/binance-cli.yml
#   name:  binance-cli
#   root:  ~/Desktop/personal/project/python/binance
#   pre_window: source ./venv/bin/activate
#   windows: 1 editor(single: editor) | 2 cmd(single: cmd) | 3 gemini(single: gemini) | 4 postgres(main-vertical: cmd 1|cmd 2) | 5 web app(main-vertical: cmd 1|cmd 2) | 6 backtest config(main-vertical: cmd 1|cmd 2)
#
# Generated by migration-herdr/generate.rb. Re-run the generator with
# FORCE=1 to regenerate from the yml, or edit this file by hand and leave FORCE
# off so the generator will not overwrite it. Run it with:
#     bash ~/.config/tmuxinator/migration-herdr/binance-cli.sh
#
set -euo pipefail

# ----------------------------- configuration --------------------------------
ROOT="${HOME}/Desktop/personal/project/python/binance"   # tmuxinator `root:`
WORKSPACE_LABEL='binance-cli'
SPLIT_RATIO="0.7"      # main-* layouts => first pane is larger. If the live
                       # result looks backwards, flip it (or drop --ratio).
FOCUS_AT_END=0         # 1 = focus the new workspace when done; 0 = leave focus
TAB_INDEX_PREFIX=1     # 1 = label tabs "<n> <name>"; 0 = bare names

# ----------------------------- preconditions -------------------------------
command -v herdr >/dev/null 2>&1 || { echo "error: 'herdr' not found in PATH" >&2; exit 1; }
command -v jq    >/dev/null 2>&1 || { echo "error: 'jq' not found in PATH"    >&2; exit 1; }
[ -d "$ROOT" ] || { echo "error: root dir not found: $ROOT" >&2; exit 1; }
# plan: what the yml asks for, and anything obviously unavailable here.
plan() { printf "%s\n" "$*"; }
for d in '/Users/lotp/Desktop/personal/project/python/binance'; do
  [ -d "$d" ] || plan "warn: missing dir in yml: $d";
done
for c in 'psql' 'uvicorn' 'npm'; do
  command -v "$c" >/dev/null 2>&1 || plan "warn: command not on PATH: $c";
done

# extract a jq path from a JSON string  ->  jget '<jq path>' '<json>'
jget() { printf '%s' "$2" | jq -r "$1"; }

# name a tab in creation order, optionally with an index prefix
TAB_INDEX=0
name_tab() { # name_tab '<tab_id>' '<name>'
  TAB_INDEX=$((TAB_INDEX + 1))
  local label="$2"
  if [ "$TAB_INDEX_PREFIX" = "1" ]; then label="$TAB_INDEX $label"; fi
  herdr tab rename "$1" "$label" >/dev/null
  printf '%s\n' "$label"
}

# guard: don't stack a second workspace with this label (tmuxinator refuses to
# restart a project that is already running).
existing="$(herdr workspace list 2>/dev/null | jq -r --arg l "$WORKSPACE_LABEL" '.result.workspaces[]? | select(.label==$l) | .workspace_id' || true)"
if [ -n "$existing" ]; then
  echo "error: workspace '$WORKSPACE_LABEL' already exists ($existing)." >&2
  echo "       close it (herdr workspace close $existing) or change WORKSPACE_LABEL, then re-run." >&2
  exit 1
fi

echo "==> Creating workspace '$WORKSPACE_LABEL' at $ROOT"

# ------------------- window 1: editor --------------------
ws_json="$(herdr workspace create --cwd "$ROOT" --label "$WORKSPACE_LABEL" --no-focus)"
WS_ID="$(jget '.result.workspace.workspace_id' "$ws_json")"
TAB1_ID="$(jget '.result.tab.tab_id' "$ws_json")"
PANE1_1="$(jget '.result.root_pane.pane_id' "$ws_json")"

name_tab "$TAB1_ID" 'editor'

herdr pane rename "$PANE1_1" 'editor' >/dev/null
herdr pane run "$PANE1_1" 'source ./venv/bin/activate' >/dev/null
herdr pane run "$PANE1_1" 'export VIM_SESSION=~/.config/nvim/session/algo-trade-binance.vim' >/dev/null
herdr pane run "$PANE1_1" 'vim -S $VIM_SESSION' >/dev/null

# ------------------- window 2: cmd --------------------
tab2_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'cmd' --no-focus)"
TAB2_ID="$(jget '.result.tab.tab_id' "$tab2_json")"
PANE2_1="$(jget '.result.root_pane.pane_id' "$tab2_json")"

name_tab "$TAB2_ID" 'cmd'

herdr pane rename "$PANE2_1" 'cmd' >/dev/null
herdr pane run "$PANE2_1" 'source ./venv/bin/activate' >/dev/null
herdr pane run "$PANE2_1" 'git status' >/dev/null

# ------------------- window 3: gemini --------------------
tab3_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'gemini' --no-focus)"
TAB3_ID="$(jget '.result.tab.tab_id' "$tab3_json")"
PANE3_1="$(jget '.result.root_pane.pane_id' "$tab3_json")"

name_tab "$TAB3_ID" 'gemini'

herdr pane rename "$PANE3_1" 'gemini' >/dev/null
herdr pane run "$PANE3_1" 'source ./venv/bin/activate' >/dev/null
herdr pane run "$PANE3_1" 'echo '\''gemini'\''' >/dev/null

# ------------------- window 4: postgres --------------------
tab4_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'postgres' --no-focus)"
TAB4_ID="$(jget '.result.tab.tab_id' "$tab4_json")"
PANE4_1="$(jget '.result.root_pane.pane_id' "$tab4_json")"

name_tab "$TAB4_ID" 'postgres'

herdr pane rename "$PANE4_1" 'cmd 1' >/dev/null
herdr pane run "$PANE4_1" 'source ./venv/bin/activate' >/dev/null
herdr pane run "$PANE4_1" 'export $(grep -v '\''^#'\'' .env | xargs)' >/dev/null
herdr pane run "$PANE4_1" 'psql postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:$POSTGRES_PORT/$POSTGRES_DB' >/dev/null

pane4_2_json="$(herdr pane split "$PANE4_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE4_2="$(jget '.result.pane.pane_id' "$pane4_2_json")"

herdr pane rename "$PANE4_2" 'cmd 2' >/dev/null
herdr pane run "$PANE4_2" 'source ./venv/bin/activate' >/dev/null
herdr pane run "$PANE4_2" '$(readlink -f $(which postgres)) -D postgres -p 7860' >/dev/null

# ------------------- window 5: web app --------------------
tab5_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'web app' --no-focus)"
TAB5_ID="$(jget '.result.tab.tab_id' "$tab5_json")"
PANE5_1="$(jget '.result.root_pane.pane_id' "$tab5_json")"

name_tab "$TAB5_ID" 'web app'

herdr pane rename "$PANE5_1" 'cmd 1' >/dev/null
herdr pane run "$PANE5_1" 'source ./venv/bin/activate' >/dev/null
herdr pane run "$PANE5_1" 'cd webapp/backend' >/dev/null
herdr pane run "$PANE5_1" 'uvicorn main:app --reload' >/dev/null

pane5_2_json="$(herdr pane split "$PANE5_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE5_2="$(jget '.result.pane.pane_id' "$pane5_2_json")"

herdr pane rename "$PANE5_2" 'cmd 2' >/dev/null
herdr pane run "$PANE5_2" 'source ./venv/bin/activate' >/dev/null
herdr pane run "$PANE5_2" 'cd webapp/backend' >/dev/null
herdr pane run "$PANE5_2" 'npm run dev' >/dev/null

# ------------------- window 6: backtest config --------------------
tab6_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'backtest config' --no-focus)"
TAB6_ID="$(jget '.result.tab.tab_id' "$tab6_json")"
PANE6_1="$(jget '.result.root_pane.pane_id' "$tab6_json")"

name_tab "$TAB6_ID" 'backtest config'

herdr pane rename "$PANE6_1" 'cmd 1' >/dev/null
herdr pane run "$PANE6_1" 'source ./venv/bin/activate' >/dev/null
herdr pane run "$PANE6_1" 'vim' >/dev/null

pane6_2_json="$(herdr pane split "$PANE6_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE6_2="$(jget '.result.pane.pane_id' "$pane6_2_json")"

herdr pane rename "$PANE6_2" 'cmd 2' >/dev/null
herdr pane run "$PANE6_2" 'source ./venv/bin/activate' >/dev/null
herdr pane run "$PANE6_2" 'cd ../bt-config' >/dev/null
herdr pane run "$PANE6_2" 'git status' >/dev/null

if [ "$FOCUS_AT_END" = "1" ]; then
  herdr workspace focus "$WS_ID" >/dev/null
fi

# ----------------------------- summary --------------------------------------
echo "==> Done. workspace '$WORKSPACE_LABEL' ($WS_ID):"
herdr workspace list 2>/dev/null \
  | jq -r --arg l "$WORKSPACE_LABEL" \
        '.result.workspaces[] | select(.label==$l)
         | "  workspace \(.workspace_id)  tabs=\(.tab_count)  panes=\(.pane_count)  active=\(.active_tab_id)"'
echo "  tabs:"
herdr tab list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.tabs[]? | "    \(.tab_id)  #\(.number)  \(.label)"' || true
echo "  panes:"
herdr pane list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.panes[]? | "    \(.pane_id)  tab=\(.tab_id)  label=\(.label)  cwd=\(.foreground_cwd)"' || true
