#!/usr/bin/env bash
#
# freq-trade.sh — recreate the tmuxinator `freqtrade` project inside Herdr.
#
# Source of truth: ~/.config/tmuxinator/freq-trade.yml
#   name:  freqtrade
#   root:  ~/Desktop/personal/project/python/freqtrade
#   pre_window: source ./.venv/bin/activate
#   windows: 1 editor(single: editor) | 2 cmd(main-vertical: cmd 1|cmd 2) | 3 v2ray(single: v2ray)
#
# Generated by migration-herdr/generate.rb. Re-run the generator with
# FORCE=1 to regenerate from the yml, or edit this file by hand and leave FORCE
# off so the generator will not overwrite it. Run it with:
#     bash ~/.config/tmuxinator/migration-herdr/freq-trade.sh
#
set -euo pipefail

# ----------------------------- configuration --------------------------------
ROOT="${HOME}/Desktop/personal/project/python/freqtrade"   # tmuxinator `root:`
WORKSPACE_LABEL='freqtrade'
SPLIT_RATIO="0.7"      # main-* layouts => first pane is larger. If the live
                       # result looks backwards, flip it (or drop --ratio).
FOCUS_AT_END=0         # 1 = focus the new workspace when done; 0 = leave focus
TAB_INDEX_PREFIX=1     # 1 = label tabs "<n> <name>"; 0 = bare names

# ----------------------------- preconditions -------------------------------
command -v herdr >/dev/null 2>&1 || { echo "error: 'herdr' not found in PATH" >&2; exit 1; }
command -v jq    >/dev/null 2>&1 || { echo "error: 'jq' not found in PATH"    >&2; exit 1; }
[ -d "$ROOT" ] || { echo "error: root dir not found: $ROOT" >&2; exit 1; }
# plan: what the yml asks for, and anything obviously unavailable here.
plan() { printf "%s\n" "$*"; }
for d in '/Users/lotp/Desktop/personal/project/python/freqtrade'; do
  [ -d "$d" ] || plan "warn: missing dir in yml: $d";
done
for c in 'freqtrade' 'python3' 'v2ray'; do
  command -v "$c" >/dev/null 2>&1 || plan "warn: command not on PATH: $c";
done

# extract a jq path from a JSON string  ->  jget '<jq path>' '<json>'
jget() { printf '%s' "$2" | jq -r "$1"; }

# name a tab in creation order, optionally with an index prefix
TAB_INDEX=0
name_tab() { # name_tab '<tab_id>' '<name>'
  TAB_INDEX=$((TAB_INDEX + 1))
  local label="$2"
  if [ "$TAB_INDEX_PREFIX" = "1" ]; then label="$TAB_INDEX $label"; fi
  herdr tab rename "$1" "$label" >/dev/null
  printf '%s\n' "$label"
}

# guard: don't stack a second workspace with this label (tmuxinator refuses to
# restart a project that is already running).
existing="$(herdr workspace list 2>/dev/null | jq -r --arg l "$WORKSPACE_LABEL" '.result.workspaces[]? | select(.label==$l) | .workspace_id' || true)"
if [ -n "$existing" ]; then
  echo "error: workspace '$WORKSPACE_LABEL' already exists ($existing)." >&2
  echo "       close it (herdr workspace close $existing) or change WORKSPACE_LABEL, then re-run." >&2
  exit 1
fi

echo "==> Creating workspace '$WORKSPACE_LABEL' at $ROOT"

# ------------------- window 1: editor --------------------
ws_json="$(herdr workspace create --cwd "$ROOT" --label "$WORKSPACE_LABEL" --no-focus)"
WS_ID="$(jget '.result.workspace.workspace_id' "$ws_json")"
TAB1_ID="$(jget '.result.tab.tab_id' "$ws_json")"
PANE1_1="$(jget '.result.root_pane.pane_id' "$ws_json")"

name_tab "$TAB1_ID" 'editor'

herdr pane rename "$PANE1_1" 'editor' >/dev/null
herdr pane run "$PANE1_1" 'source ./.venv/bin/activate' >/dev/null
herdr pane run "$PANE1_1" 'export VIM_SESSION=~/.config/nvim/session/freqtrade.vim' >/dev/null
herdr pane run "$PANE1_1" 'vim -S $VIM_SESSION' >/dev/null

# ------------------- window 2: cmd --------------------
tab2_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'cmd' --no-focus)"
TAB2_ID="$(jget '.result.tab.tab_id' "$tab2_json")"
PANE2_1="$(jget '.result.root_pane.pane_id' "$tab2_json")"

name_tab "$TAB2_ID" 'cmd'

herdr pane rename "$PANE2_1" 'cmd 1' >/dev/null
herdr pane run "$PANE2_1" 'source ./.venv/bin/activate' >/dev/null
herdr pane run "$PANE2_1" 'git status' >/dev/null

pane2_2_json="$(herdr pane split "$PANE2_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE2_2="$(jget '.result.pane.pane_id' "$pane2_2_json")"

herdr pane rename "$PANE2_2" 'cmd 2' >/dev/null
herdr pane run "$PANE2_2" 'source ./.venv/bin/activate' >/dev/null
herdr pane run "$PANE2_2" 'freqtrade list-strategies' >/dev/null

# ------------------- window 3: v2ray --------------------
tab3_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'v2ray' --no-focus)"
TAB3_ID="$(jget '.result.tab.tab_id' "$tab3_json")"
PANE3_1="$(jget '.result.root_pane.pane_id' "$tab3_json")"

name_tab "$TAB3_ID" 'v2ray'

herdr pane rename "$PANE3_1" 'v2ray' >/dev/null
herdr pane run "$PANE3_1" 'source ./.venv/bin/activate' >/dev/null
herdr pane run "$PANE3_1" 'cd ../v2ray' >/dev/null
herdr pane run "$PANE3_1" 'python3 tmp.py' >/dev/null
herdr pane run "$PANE3_1" 'v2ray run -c kk.json' >/dev/null

if [ "$FOCUS_AT_END" = "1" ]; then
  herdr workspace focus "$WS_ID" >/dev/null
fi

# ----------------------------- summary --------------------------------------
echo "==> Done. workspace '$WORKSPACE_LABEL' ($WS_ID):"
herdr workspace list 2>/dev/null \
  | jq -r --arg l "$WORKSPACE_LABEL" \
        '.result.workspaces[] | select(.label==$l)
         | "  workspace \(.workspace_id)  tabs=\(.tab_count)  panes=\(.pane_count)  active=\(.active_tab_id)"'
echo "  tabs:"
herdr tab list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.tabs[]? | "    \(.tab_id)  #\(.number)  \(.label)"' || true
echo "  panes:"
herdr pane list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.panes[]? | "    \(.pane_id)  tab=\(.tab_id)  label=\(.label)  cwd=\(.foreground_cwd)"' || true
