#!/usr/bin/env ruby
#
# generate.rb — turn a tmuxinator project file into a Herdr layout script.
#
#   ruby ~/.config/tmuxinator/migration-herdr/generate.rb            # all *.yml
#   ruby ~/.config/tmuxinator/migration-herdr/generate.rb blog.yml   # one project
#   FORCE=1 ruby .../generate.rb                                     # overwrite existing
#
# Without FORCE, an existing <project>.sh is never touched: hand-edited scripts
# (proxmox.sh, resume.sh) keep their decisions.
#
# Mapping (tmuxinator -> herdr CLI):
#   name/root              -> workspace create --label/--cwd
#   window                 -> tab (first window's tab is the workspace root tab)
#   window list item = [c] -> one pane running each c with `pane run`
#   panes: + layout        -> tab create + `pane split` chain
#     main-vertical        -> panes[0] wide left, rest stacked in the right column
#     main-horizontal      -> panes[0] tall top, rest in a row below
#     even-horizontal      -> equal-width columns
#   window root:           -> --cwd override for that tab and its splits
#   pre_window             -> replayed into every pane, before that pane's commands
#
# Faithful by design: commands are copied verbatim (one `pane run` per yml line,
# like tmuxinator sending each line), including stale or broken ones. The script
# prints a plan table so drift in the yml is visible, not silently fixed.
#
require 'yaml'

TMUX_DIR = File.expand_path('~/.config/tmuxinator')
OUT_DIR  = File.join(TMUX_DIR, 'migration-herdr')

# ---------- helpers -------------------------------------------------------
def sq(s)
  "'" + s.to_s.gsub("'") { "'\\''" } + "'"
end

def dquote(s)
  '"' + s.to_s.gsub('\\') { '\\\\' }.gsub('"') { '\\"' }
        .gsub('`') { '\\`' } + '"'
end

# translate a tmuxinator path (may start with ~) into a bash value
def bash_path(p)
  p = p.to_s.strip
  return '${HOME}' if p == '~'
  return "${HOME}/#{p.sub(%r{^~/}, '')}" if p.start_with?('~/')
  p
end

# ROOT-style assignment: a leading ~ becomes an expanding ${HOME}; the rest is
# escaped for a bash double-quoted string (the $ of ${HOME} must stay live).
def root_assign(var, p)
  p = p.to_s.strip
  if p == '~'
    "#{var}=\"${HOME}\""
  elsif p.start_with?('~/')
    rest = p.sub(%r{^~/}, '').gsub('\\') { '\\\\' }.gsub('"') { '\\"' }.gsub('`') { '\\`' }
    "#{var}=\"${HOME}/#{rest}\""
  else
    "#{var}=#{dquote(p)}"
  end
end

def expand(p)
  p = p.to_s
  return File.expand_path(p) if p.start_with?('~')
  p
end

def sq_path(p)
  sq(bash_path(p))
end

# normalize one window entry into { title:, root:, layout:, panes: [[label, [cmds]]] }
def parse_window(entry)
  title, body = entry.first
  w = { title: title.to_s, root: nil, layout: nil, panes: [] }
  case body
  when nil
    w[:panes] = [[w[:title], []]]
  when Array
    w[:panes] = [[w[:title], body.map(&:to_s)]]
  when Hash
    w[:root]   = body['root']   if body['root']
    w[:layout] = body['layout'] if body['layout']
    (body['panes'] || []).each do |pane|
      case pane
      when Hash
        pane.each { |label, cmds| w[:panes] << [label.to_s, Array(cmds).map(&:to_s)] }
      else
        w[:panes] << [nil, [pane.to_s]]
      end
    end
    w[:panes] = [[w[:title], []]] if w[:panes].empty?
  when String
    w[:panes] = [[w[:title], [body]]]
  end
  w
end

# ---------- emit ---------------------------------------------------------
def emit(out, file, cfg)
  windows = cfg[:windows]
  name    = cfg[:name]
  root    = cfg[:root]
  pre     = cfg[:pre_window]

  out.puts "#!/usr/bin/env bash"
  out.puts "#"
  out.puts "# #{file}.sh — recreate the tmuxinator `#{name}` project inside Herdr."
  out.puts "#"
  out.puts "# Source of truth: ~/.config/tmuxinator/#{file}.yml"
  out.puts "#   name:  #{name}"
  out.puts "#   root:  #{root}"
  out.puts "#   pre_window: #{pre.map { |c| c }.join(' ; ')}" unless pre.empty?
  out.puts '#   windows: ' + windows.each_with_index.map { |w, i|
    layout = w[:layout] || (w[:panes].size > 1 ? 'main-vertical(default)' : 'single')
    "#{i + 1} #{w[:title]}(#{layout}: #{w[:panes].map { |l, _| l || 'unnamed' }.join('|')})"
  }.join(' | ')
  out.puts '#'
  out.puts '# Generated by migration-herdr/generate.rb. Re-run the generator with'
  out.puts '# FORCE=1 to regenerate from the yml, or edit this file by hand and leave FORCE'
  out.puts '# off so the generator will not overwrite it. Run it with:'
  out.puts "#     bash ~/.config/tmuxinator/migration-herdr/#{file}.sh"
  out.puts '#'
  out.puts 'set -euo pipefail'
  out.puts
  out.puts '# ----------------------------- configuration --------------------------------'
  out.puts "#{root_assign('ROOT', root)}   # tmuxinator `root:`"
  out.puts "WORKSPACE_LABEL=#{sq(name)}"
  out.puts 'SPLIT_RATIO="0.7"      # main-* layouts => first pane is larger. If the live'
  out.puts '                       # result looks backwards, flip it (or drop --ratio).'
  out.puts 'FOCUS_AT_END=0         # 1 = focus the new workspace when done; 0 = leave focus'
  out.puts 'TAB_INDEX_PREFIX=1     # 1 = label tabs "<n> <name>"; 0 = bare names'
  out.puts
  out.puts '# ----------------------------- preconditions -------------------------------'
  out.puts %q{command -v herdr >/dev/null 2>&1 || { echo "error: 'herdr' not found in PATH" >&2; exit 1; }}
  out.puts %q{command -v jq    >/dev/null 2>&1 || { echo "error: 'jq' not found in PATH"    >&2; exit 1; }}
  out.puts %q{[ -d "$ROOT" ] || { echo "error: root dir not found: $ROOT" >&2; exit 1; }}
  out.puts '# plan: what the yml asks for, and anything obviously unavailable here.'
  out.puts 'plan() { printf "%s\n" "$*"; }'
  out.puts 'for d in ' + windows.map { |w| sq(expand(w[:root] || root)) }.uniq.join(' ') + '; do'
  out.puts %q{  [ -d "$d" ] || plan "warn: missing dir in yml: $d";}
  out.puts 'done'
  unless cfg[:commands].empty?
    out.puts 'for c in' + cfg[:commands].map { |c| ' ' + sq(c) }.join + '; do'
    out.puts %q{  command -v "$c" >/dev/null 2>&1 || plan "warn: command not on PATH: $c";}
    out.puts 'done'
  end
  out.puts
  out.puts '# extract a jq path from a JSON string  ->  jget \'<jq path>\' \'<json>\''
  out.puts %q{jget() { printf '%s' "$2" | jq -r "$1"; }}
  out.puts
  out.puts '# name a tab in creation order, optionally with an index prefix'
  out.puts 'TAB_INDEX=0'
  out.puts 'name_tab() { # name_tab \'<tab_id>\' \'<name>\''
  out.puts '  TAB_INDEX=$((TAB_INDEX + 1))'
  out.puts '  local label="$2"'
  out.puts '  if [ "$TAB_INDEX_PREFIX" = "1" ]; then label="$TAB_INDEX $label"; fi'
  out.puts '  herdr tab rename "$1" "$label" >/dev/null'
  out.puts '  printf \'%s\\n\' "$label"'
  out.puts '}'
  out.puts
  out.puts '# guard: don\'t stack a second workspace with this label (tmuxinator refuses to'
  out.puts '# restart a project that is already running).'
  out.puts %q{existing="$(herdr workspace list 2>/dev/null | jq -r --arg l "$WORKSPACE_LABEL" '.result.workspaces[]? | select(.label==$l) | .workspace_id' || true)"}
  out.puts 'if [ -n "$existing" ]; then'
  out.puts %q{  echo "error: workspace '$WORKSPACE_LABEL' already exists ($existing)." >&2}
  out.puts %q{  echo "       close it (herdr workspace close $existing) or change WORKSPACE_LABEL, then re-run." >&2}
  out.puts '  exit 1'
  out.puts 'fi'
  out.puts
  out.puts %q{echo "==> Creating workspace '$WORKSPACE_LABEL' at $ROOT"}
  out.puts

  windows.each_with_index do |w, wi|
    n = wi + 1
    wroot = w[:root] ? %Q{"$ROOT_#{n}"} : '"$ROOT"'
    out.puts "# ------------------- window #{n}: #{w[:title]}#{w[:root] ? " (root: #{w[:root]})" : ''} #{'-' * 20}"
    out.puts root_assign("ROOT_#{n}", w[:root]) + "   # this window's `root:` override" if w[:root]

    if n == 1
      out.puts %q{ws_json="$(herdr workspace create --cwd } + wroot + %q{ --label "$WORKSPACE_LABEL" --no-focus)"}
      out.puts "WS_ID=\"$(jget '.result.workspace.workspace_id' \"$ws_json\")\""
      out.puts "TAB#{n}_ID=\"$(jget '.result.tab.tab_id' \"$ws_json\")\""
      out.puts "PANE#{n}_1=\"$(jget '.result.root_pane.pane_id' \"$ws_json\")\""
    else
      out.puts "tab#{n}_json=\"$(herdr tab create --workspace \"$WS_ID\" --cwd #{wroot} --label #{sq(w[:title])} --no-focus)\""
      out.puts "TAB#{n}_ID=\"$(jget '.result.tab.tab_id' \"$tab#{n}_json\")\""
      out.puts "PANE#{n}_1=\"$(jget '.result.root_pane.pane_id' \"$tab#{n}_json\")\""
    end
    out.puts
    out.puts "name_tab \"$TAB#{n}_ID\" #{sq(w[:title])}"
    out.puts

    layout = w[:layout] || 'main-vertical'
    w[:panes].each_with_index do |(label, cmds), pi|
      p = pi + 1
      if p > 1
        dir, ratio =
          case layout
          when 'even-horizontal' then ['right', nil]
          when 'main-horizontal' then (p == 2 ? ['down', '"$SPLIT_RATIO"'] : ['right', nil])
          else (p == 2 ? ['right', '"$SPLIT_RATIO"'] : ['down', nil])
          end
        src = "\"$PANE#{n}_#{p - 1}\""
        out.puts "pane#{n}_#{p}_json=\"$(herdr pane split #{src} --direction #{dir}#{ratio ? " --ratio #{ratio}" : ''} --cwd #{wroot} --no-focus)\""
        out.puts "PANE#{n}_#{p}=\"$(jget '.result.pane.pane_id' \"$pane#{n}_#{p}_json\")\""
        out.puts
      end
      out.puts "herdr pane rename \"$PANE#{n}_#{p}\" #{sq(label || w[:title])} >/dev/null"
      pre.each { |c| out.puts "herdr pane run \"$PANE#{n}_#{p}\" #{sq(c)} >/dev/null" }
      cmds.each { |c| out.puts "herdr pane run \"$PANE#{n}_#{p}\" #{sq(c)} >/dev/null" }
      out.puts unless pi == w[:panes].size - 1
    end
    out.puts
  end

  out.puts 'if [ "$FOCUS_AT_END" = "1" ]; then'
  out.puts '  herdr workspace focus "$WS_ID" >/dev/null'
  out.puts 'fi'
  out.puts
  out.puts '# ----------------------------- summary --------------------------------------'
  out.puts %q{echo "==> Done. workspace '$WORKSPACE_LABEL' ($WS_ID):"}
  out.puts 'herdr workspace list 2>/dev/null \\'
  out.puts '  | jq -r --arg l "$WORKSPACE_LABEL" \\'
  out.puts %q{        '.result.workspaces[] | select(.label==$l)}
  out.puts %q{         | "  workspace \(.workspace_id)  tabs=\(.tab_count)  panes=\(.pane_count)  active=\(.active_tab_id)"'}
  out.puts 'echo "  tabs:"'
  out.puts 'herdr tab list --workspace "$WS_ID" 2>/dev/null \\'
  out.puts %q{  | jq -r '.result.tabs[]? | "    \(.tab_id)  #\(.number)  \(.label)"' || true}
  out.puts 'echo "  panes:"'
  out.puts 'herdr pane list --workspace "$WS_ID" 2>/dev/null \\'
  out.puts %q{  | jq -r '.result.panes[]? | "    \(.pane_id)  tab=\(.tab_id)  label=\(.label)  cwd=\(.foreground_cwd)"' || true}
end

# ---------- main ---------------------------------------------------------
args = ARGV.reject { |a| a.start_with?('-') }
files = args.empty? ? Dir.glob(File.join(TMUX_DIR, '*.yml')).map { |f| File.basename(f, '.yml') } : args.map { |f| File.basename(f, '.yml') }

# commands that look like real binaries we can check for existence
IGNORED_FIRST_TOKEN = %w[export cd ls cat echo source readlink ps grep awk xargs sleep git vim nvim pi kill mkdir rm printf].freeze

files.each do |file|
  src = File.join(TMUX_DIR, "#{file}.yml")
  abort "error: no such tmuxinator file: #{src}" unless File.exist?(src)
  data = YAML.load_file(src)
  windows_raw = data['windows'] || data['tabs'] || []
  cfg = {
    name: data['name'] || file,
    root: data['root'] || Dir.pwd,
    pre_window: Array(data['pre_window']).map(&:to_s),
    windows: windows_raw.map { |w| parse_window(w) },
  }
  cmds = (cfg[:pre_window] + cfg[:windows].flat_map { |w| w[:panes].flat_map { |(_, c)| c } })
         .map(&:strip).reject(&:empty?)
         .map { |c| c.split(/\s+/).first }
         .reject { |c| IGNORED_FIRST_TOKEN.include?(c) }
         .reject { |c| c.include?('=') || c.start_with?('$', '(', '%') }
         .uniq
  cfg[:commands] = cmds

  dst = File.join(OUT_DIR, "#{file}.sh")
  if File.exist?(dst)
    generated = File.read(dst).include?('Generated by migration-herdr/generate.rb')
    if !generated
      puts "skip: #{file}.sh is hand-written (generator never overwrites it)"
      next
    elsif ENV['FORCE'] != '1'
      puts "skip: #{file}.sh exists (FORCE=1 to regenerate)"
      next
    end
  end
  require 'stringio'
  buf = StringIO.new
  emit(buf, file, cfg)
  File.write(dst, buf.string)
  File.chmod(0o755, dst)
  puts "wrote: #{dst}  (#{cfg[:windows].size} windows, #{cfg[:windows].sum { |w| w[:panes].size }} panes)"
end
