#!/usr/bin/env bash
#
# learn-anything.sh — recreate the tmuxinator `Learn Anthing` project inside Herdr.
#
# Source of truth: ~/.config/tmuxinator/learn-anything.yml
#   name:  Learn Anthing
#   root:  ~/Desktop/Personal/project/javascript/learn-anything
#   pre_window: export SESSION_HOME="~/.config/nvim/session/learn-anything"
#   windows: 1 FE(even-horizontal: pi|vim) | 2 FE CMD(main-vertical: cmd|db|dev server) | 3 Sandbox(even-horizontal: pi|vim) | 4 Sandbox CMD(main-vertical: cmd|dev server) | 5 BE(even-horizontal: pi|vim) | 6 BE CMD(main-vertical: cmd|dev server)
#
# Generated by migration-herdr/generate.rb. Re-run the generator with
# FORCE=1 to regenerate from the yml, or edit this file by hand and leave FORCE
# off so the generator will not overwrite it. Run it with:
#     bash ~/.config/tmuxinator/migration-herdr/learn-anything.sh
#
set -euo pipefail

# ----------------------------- configuration --------------------------------
ROOT="${HOME}/Desktop/Personal/project/javascript/learn-anything"   # tmuxinator `root:`
WORKSPACE_LABEL='Learn Anthing'
SPLIT_RATIO="0.7"      # main-* layouts => first pane is larger. If the live
                       # result looks backwards, flip it (or drop --ratio).
FOCUS_AT_END=0         # 1 = focus the new workspace when done; 0 = leave focus
TAB_INDEX_PREFIX=1     # 1 = label tabs "<n> <name>"; 0 = bare names

# ----------------------------- preconditions -------------------------------
command -v herdr >/dev/null 2>&1 || { echo "error: 'herdr' not found in PATH" >&2; exit 1; }
command -v jq    >/dev/null 2>&1 || { echo "error: 'jq' not found in PATH"    >&2; exit 1; }
[ -d "$ROOT" ] || { echo "error: root dir not found: $ROOT" >&2; exit 1; }
# plan: what the yml asks for, and anything obviously unavailable here.
plan() { printf "%s\n" "$*"; }
for d in '/Users/lotp/Desktop/Personal/project/javascript/learn-anything' '/Users/lotp/Desktop/Personal/project/javascript/learn-anything-sandbox' '/Users/lotp/Desktop/Personal/project/python/learn-anything-backend'; do
  [ -d "$d" ] || plan "warn: missing dir in yml: $d";
done
for c in 'podman' 'npm' 'uv'; do
  command -v "$c" >/dev/null 2>&1 || plan "warn: command not on PATH: $c";
done

# extract a jq path from a JSON string  ->  jget '<jq path>' '<json>'
jget() { printf '%s' "$2" | jq -r "$1"; }

# name a tab in creation order, optionally with an index prefix
TAB_INDEX=0
name_tab() { # name_tab '<tab_id>' '<name>'
  TAB_INDEX=$((TAB_INDEX + 1))
  local label="$2"
  if [ "$TAB_INDEX_PREFIX" = "1" ]; then label="$TAB_INDEX $label"; fi
  herdr tab rename "$1" "$label" >/dev/null
  printf '%s\n' "$label"
}

# guard: don't stack a second workspace with this label (tmuxinator refuses to
# restart a project that is already running).
existing="$(herdr workspace list 2>/dev/null | jq -r --arg l "$WORKSPACE_LABEL" '.result.workspaces[]? | select(.label==$l) | .workspace_id' || true)"
if [ -n "$existing" ]; then
  echo "error: workspace '$WORKSPACE_LABEL' already exists ($existing)." >&2
  echo "       close it (herdr workspace close $existing) or change WORKSPACE_LABEL, then re-run." >&2
  exit 1
fi

echo "==> Creating workspace '$WORKSPACE_LABEL' at $ROOT"

# ------------------- window 1: FE --------------------
ws_json="$(herdr workspace create --cwd "$ROOT" --label "$WORKSPACE_LABEL" --no-focus)"
WS_ID="$(jget '.result.workspace.workspace_id' "$ws_json")"
TAB1_ID="$(jget '.result.tab.tab_id' "$ws_json")"
PANE1_1="$(jget '.result.root_pane.pane_id' "$ws_json")"

name_tab "$TAB1_ID" 'FE'

herdr pane rename "$PANE1_1" 'pi' >/dev/null
herdr pane run "$PANE1_1" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE1_1" 'pi' >/dev/null

pane1_2_json="$(herdr pane split "$PANE1_1" --direction right --cwd "$ROOT" --no-focus)"
PANE1_2="$(jget '.result.pane.pane_id' "$pane1_2_json")"

herdr pane rename "$PANE1_2" 'vim' >/dev/null
herdr pane run "$PANE1_2" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE1_2" 'export VIM_SESSION=$SESSION_HOME/fe.vim' >/dev/null
herdr pane run "$PANE1_2" 'vim -S $VIM_SESSION' >/dev/null

# ------------------- window 2: FE CMD --------------------
tab2_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'FE CMD' --no-focus)"
TAB2_ID="$(jget '.result.tab.tab_id' "$tab2_json")"
PANE2_1="$(jget '.result.root_pane.pane_id' "$tab2_json")"

name_tab "$TAB2_ID" 'FE CMD'

herdr pane rename "$PANE2_1" 'cmd' >/dev/null
herdr pane run "$PANE2_1" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE2_1" 'git status' >/dev/null

pane2_2_json="$(herdr pane split "$PANE2_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE2_2="$(jget '.result.pane.pane_id' "$pane2_2_json")"

herdr pane rename "$PANE2_2" 'db' >/dev/null
herdr pane run "$PANE2_2" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE2_2" 'podman compose up' >/dev/null

pane2_3_json="$(herdr pane split "$PANE2_2" --direction down --cwd "$ROOT" --no-focus)"
PANE2_3="$(jget '.result.pane.pane_id' "$pane2_3_json")"

herdr pane rename "$PANE2_3" 'dev server' >/dev/null
herdr pane run "$PANE2_3" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE2_3" 'npm run dev' >/dev/null

# ------------------- window 3: Sandbox (root: ~/Desktop/Personal/project/javascript/learn-anything-sandbox) --------------------
ROOT_3="${HOME}/Desktop/Personal/project/javascript/learn-anything-sandbox"   # this window's `root:` override
tab3_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT_3" --label 'Sandbox' --no-focus)"
TAB3_ID="$(jget '.result.tab.tab_id' "$tab3_json")"
PANE3_1="$(jget '.result.root_pane.pane_id' "$tab3_json")"

name_tab "$TAB3_ID" 'Sandbox'

herdr pane rename "$PANE3_1" 'pi' >/dev/null
herdr pane run "$PANE3_1" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE3_1" 'pi' >/dev/null

pane3_2_json="$(herdr pane split "$PANE3_1" --direction right --cwd "$ROOT_3" --no-focus)"
PANE3_2="$(jget '.result.pane.pane_id' "$pane3_2_json")"

herdr pane rename "$PANE3_2" 'vim' >/dev/null
herdr pane run "$PANE3_2" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE3_2" 'export VIM_SESSION=$SESSION_HOME/sandbox.vim' >/dev/null
herdr pane run "$PANE3_2" 'vim -S $VIM_SESSION' >/dev/null

# ------------------- window 4: Sandbox CMD (root: ~/Desktop/Personal/project/javascript/learn-anything-sandbox) --------------------
ROOT_4="${HOME}/Desktop/Personal/project/javascript/learn-anything-sandbox"   # this window's `root:` override
tab4_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT_4" --label 'Sandbox CMD' --no-focus)"
TAB4_ID="$(jget '.result.tab.tab_id' "$tab4_json")"
PANE4_1="$(jget '.result.root_pane.pane_id' "$tab4_json")"

name_tab "$TAB4_ID" 'Sandbox CMD'

herdr pane rename "$PANE4_1" 'cmd' >/dev/null
herdr pane run "$PANE4_1" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE4_1" 'git status' >/dev/null

pane4_2_json="$(herdr pane split "$PANE4_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT_4" --no-focus)"
PANE4_2="$(jget '.result.pane.pane_id' "$pane4_2_json")"

herdr pane rename "$PANE4_2" 'dev server' >/dev/null
herdr pane run "$PANE4_2" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE4_2" 'npm run dev -- -p 3001' >/dev/null

# ------------------- window 5: BE (root: ~/Desktop/Personal/project/python/learn-anything-backend) --------------------
ROOT_5="${HOME}/Desktop/Personal/project/python/learn-anything-backend"   # this window's `root:` override
tab5_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT_5" --label 'BE' --no-focus)"
TAB5_ID="$(jget '.result.tab.tab_id' "$tab5_json")"
PANE5_1="$(jget '.result.root_pane.pane_id' "$tab5_json")"

name_tab "$TAB5_ID" 'BE'

herdr pane rename "$PANE5_1" 'pi' >/dev/null
herdr pane run "$PANE5_1" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE5_1" 'pi' >/dev/null

pane5_2_json="$(herdr pane split "$PANE5_1" --direction right --cwd "$ROOT_5" --no-focus)"
PANE5_2="$(jget '.result.pane.pane_id' "$pane5_2_json")"

herdr pane rename "$PANE5_2" 'vim' >/dev/null
herdr pane run "$PANE5_2" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE5_2" 'export VIM_SESSION=$SESSION_HOME/be.vim' >/dev/null
herdr pane run "$PANE5_2" 'vim -S $VIM_SESSION' >/dev/null

# ------------------- window 6: BE CMD (root: ~/Desktop/Personal/project/python/learn-anything-backend) --------------------
ROOT_6="${HOME}/Desktop/Personal/project/python/learn-anything-backend"   # this window's `root:` override
tab6_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT_6" --label 'BE CMD' --no-focus)"
TAB6_ID="$(jget '.result.tab.tab_id' "$tab6_json")"
PANE6_1="$(jget '.result.root_pane.pane_id' "$tab6_json")"

name_tab "$TAB6_ID" 'BE CMD'

herdr pane rename "$PANE6_1" 'cmd' >/dev/null
herdr pane run "$PANE6_1" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE6_1" 'git status' >/dev/null

pane6_2_json="$(herdr pane split "$PANE6_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT_6" --no-focus)"
PANE6_2="$(jget '.result.pane.pane_id' "$pane6_2_json")"

herdr pane rename "$PANE6_2" 'dev server' >/dev/null
herdr pane run "$PANE6_2" 'export SESSION_HOME="~/.config/nvim/session/learn-anything"' >/dev/null
herdr pane run "$PANE6_2" 'uv run python main.py --reload' >/dev/null

if [ "$FOCUS_AT_END" = "1" ]; then
  herdr workspace focus "$WS_ID" >/dev/null
fi

# ----------------------------- summary --------------------------------------
echo "==> Done. workspace '$WORKSPACE_LABEL' ($WS_ID):"
herdr workspace list 2>/dev/null \
  | jq -r --arg l "$WORKSPACE_LABEL" \
        '.result.workspaces[] | select(.label==$l)
         | "  workspace \(.workspace_id)  tabs=\(.tab_count)  panes=\(.pane_count)  active=\(.active_tab_id)"'
echo "  tabs:"
herdr tab list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.tabs[]? | "    \(.tab_id)  #\(.number)  \(.label)"' || true
echo "  panes:"
herdr pane list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.panes[]? | "    \(.pane_id)  tab=\(.tab_id)  label=\(.label)  cwd=\(.foreground_cwd)"' || true
