#!/usr/bin/env bash
#
# lhb-trade.sh — recreate the tmuxinator `lhb-trade` project inside Herdr.
#
# Source of truth: ~/.config/tmuxinator/lhb-trade.yml
#   name:  lhb-trade
#   root:  ~/Desktop/personal/project
#   windows: 1 be editor(single: be editor) | 2 be cmd(main-vertical: cmd|db|be server) | 3 be aider(single: be aider) | 4 fe editor(single: fe editor) | 5 fe cmd(main-vertical: cmd|dev server) | 6 fe aider(single: fe aider) | 7 script runner(single: script runner)
#
# Generated by migration-herdr/generate.rb. Re-run the generator with
# FORCE=1 to regenerate from the yml, or edit this file by hand and leave FORCE
# off so the generator will not overwrite it. Run it with:
#     bash ~/.config/tmuxinator/migration-herdr/lhb-trade.sh
#
set -euo pipefail

# ----------------------------- configuration --------------------------------
ROOT="${HOME}/Desktop/personal/project"   # tmuxinator `root:`
WORKSPACE_LABEL='lhb-trade'
SPLIT_RATIO="0.7"      # main-* layouts => first pane is larger. If the live
                       # result looks backwards, flip it (or drop --ratio).
FOCUS_AT_END=0         # 1 = focus the new workspace when done; 0 = leave focus
TAB_INDEX_PREFIX=1     # 1 = label tabs "<n> <name>"; 0 = bare names

# ----------------------------- preconditions -------------------------------
command -v herdr >/dev/null 2>&1 || { echo "error: 'herdr' not found in PATH" >&2; exit 1; }
command -v jq    >/dev/null 2>&1 || { echo "error: 'jq' not found in PATH"    >&2; exit 1; }
[ -d "$ROOT" ] || { echo "error: root dir not found: $ROOT" >&2; exit 1; }
# plan: what the yml asks for, and anything obviously unavailable here.
plan() { printf "%s\n" "$*"; }
for d in '/Users/lotp/Desktop/personal/project'; do
  [ -d "$d" ] || plan "warn: missing dir in yml: $d";
done
for c in 'python3' 'npm'; do
  command -v "$c" >/dev/null 2>&1 || plan "warn: command not on PATH: $c";
done

# extract a jq path from a JSON string  ->  jget '<jq path>' '<json>'
jget() { printf '%s' "$2" | jq -r "$1"; }

# name a tab in creation order, optionally with an index prefix
TAB_INDEX=0
name_tab() { # name_tab '<tab_id>' '<name>'
  TAB_INDEX=$((TAB_INDEX + 1))
  local label="$2"
  if [ "$TAB_INDEX_PREFIX" = "1" ]; then label="$TAB_INDEX $label"; fi
  herdr tab rename "$1" "$label" >/dev/null
  printf '%s\n' "$label"
}

# guard: don't stack a second workspace with this label (tmuxinator refuses to
# restart a project that is already running).
existing="$(herdr workspace list 2>/dev/null | jq -r --arg l "$WORKSPACE_LABEL" '.result.workspaces[]? | select(.label==$l) | .workspace_id' || true)"
if [ -n "$existing" ]; then
  echo "error: workspace '$WORKSPACE_LABEL' already exists ($existing)." >&2
  echo "       close it (herdr workspace close $existing) or change WORKSPACE_LABEL, then re-run." >&2
  exit 1
fi

echo "==> Creating workspace '$WORKSPACE_LABEL' at $ROOT"

# ------------------- window 1: be editor --------------------
ws_json="$(herdr workspace create --cwd "$ROOT" --label "$WORKSPACE_LABEL" --no-focus)"
WS_ID="$(jget '.result.workspace.workspace_id' "$ws_json")"
TAB1_ID="$(jget '.result.tab.tab_id' "$ws_json")"
PANE1_1="$(jget '.result.root_pane.pane_id' "$ws_json")"

name_tab "$TAB1_ID" 'be editor'

herdr pane rename "$PANE1_1" 'be editor' >/dev/null
herdr pane run "$PANE1_1" 'cd python/lhb-trade' >/dev/null
herdr pane run "$PANE1_1" 'export PYTHONPATH=$PYTHONPATH:./src' >/dev/null
herdr pane run "$PANE1_1" 'source ./env/bin/activate' >/dev/null
herdr pane run "$PANE1_1" 'export VIM_SESSION=~/.config/nvim/session/lhb-trade.vim' >/dev/null
herdr pane run "$PANE1_1" 'vim -S $VIM_SESSION' >/dev/null

# ------------------- window 2: be cmd --------------------
tab2_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'be cmd' --no-focus)"
TAB2_ID="$(jget '.result.tab.tab_id' "$tab2_json")"
PANE2_1="$(jget '.result.root_pane.pane_id' "$tab2_json")"

name_tab "$TAB2_ID" 'be cmd'

herdr pane rename "$PANE2_1" 'cmd' >/dev/null
herdr pane run "$PANE2_1" 'cd python/lhb-trade' >/dev/null
herdr pane run "$PANE2_1" 'export PYTHONPATH=$PYTHONPATH:./src' >/dev/null
herdr pane run "$PANE2_1" 'source ./env/bin/activate' >/dev/null
herdr pane run "$PANE2_1" 'git status' >/dev/null

pane2_2_json="$(herdr pane split "$PANE2_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE2_2="$(jget '.result.pane.pane_id' "$pane2_2_json")"

herdr pane rename "$PANE2_2" 'db' >/dev/null
herdr pane run "$PANE2_2" 'cd python/lhb-trade' >/dev/null
herdr pane run "$PANE2_2" '$(readlink -f $(which postgres)) -D db' >/dev/null
herdr pane run "$PANE2_2" 'echo '\''$(readlink -f $(which postgres)) -D db'\''' >/dev/null

pane2_3_json="$(herdr pane split "$PANE2_2" --direction down --cwd "$ROOT" --no-focus)"
PANE2_3="$(jget '.result.pane.pane_id' "$pane2_3_json")"

herdr pane rename "$PANE2_3" 'be server' >/dev/null
herdr pane run "$PANE2_3" 'cd python/lhb-trade' >/dev/null
herdr pane run "$PANE2_3" 'export PYTHONPATH=$PYTHONPATH:./src' >/dev/null
herdr pane run "$PANE2_3" 'source ./env/bin/activate' >/dev/null
herdr pane run "$PANE2_3" 'python3 -m fastapi dev src/main.py --port 3002' >/dev/null

# ------------------- window 3: be aider --------------------
tab3_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'be aider' --no-focus)"
TAB3_ID="$(jget '.result.tab.tab_id' "$tab3_json")"
PANE3_1="$(jget '.result.root_pane.pane_id' "$tab3_json")"

name_tab "$TAB3_ID" 'be aider'

herdr pane rename "$PANE3_1" 'be aider' >/dev/null
herdr pane run "$PANE3_1" 'cd python/lhb-trade' >/dev/null
herdr pane run "$PANE3_1" 'export PYTHONPATH=$PYTHONPATH:./src' >/dev/null
herdr pane run "$PANE3_1" 'echo '\''aider --model ollama_chat/qwen2.5-coder:14b --read convention.md --show-diffs --no-auto-commit --chat-mode code --vim .'\''' >/dev/null

# ------------------- window 4: fe editor --------------------
tab4_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'fe editor' --no-focus)"
TAB4_ID="$(jget '.result.tab.tab_id' "$tab4_json")"
PANE4_1="$(jget '.result.root_pane.pane_id' "$tab4_json")"

name_tab "$TAB4_ID" 'fe editor'

herdr pane rename "$PANE4_1" 'fe editor' >/dev/null
herdr pane run "$PANE4_1" 'cd javascript/lfb-trade-fe' >/dev/null
herdr pane run "$PANE4_1" 'export VIM_SESSION=~/.config/nvim/session/lhb-trade-fe.vim' >/dev/null
herdr pane run "$PANE4_1" 'vim -S $VIM_SESSION' >/dev/null

# ------------------- window 5: fe cmd --------------------
tab5_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'fe cmd' --no-focus)"
TAB5_ID="$(jget '.result.tab.tab_id' "$tab5_json")"
PANE5_1="$(jget '.result.root_pane.pane_id' "$tab5_json")"

name_tab "$TAB5_ID" 'fe cmd'

herdr pane rename "$PANE5_1" 'cmd' >/dev/null
herdr pane run "$PANE5_1" 'cd javascript/lfb-trade-fe' >/dev/null
herdr pane run "$PANE5_1" 'git status' >/dev/null

pane5_2_json="$(herdr pane split "$PANE5_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE5_2="$(jget '.result.pane.pane_id' "$pane5_2_json")"

herdr pane rename "$PANE5_2" 'dev server' >/dev/null
herdr pane run "$PANE5_2" 'cd javascript/lfb-trade-fe' >/dev/null
herdr pane run "$PANE5_2" 'npm run dev' >/dev/null

# ------------------- window 6: fe aider --------------------
tab6_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'fe aider' --no-focus)"
TAB6_ID="$(jget '.result.tab.tab_id' "$tab6_json")"
PANE6_1="$(jget '.result.root_pane.pane_id' "$tab6_json")"

name_tab "$TAB6_ID" 'fe aider'

herdr pane rename "$PANE6_1" 'fe aider' >/dev/null
herdr pane run "$PANE6_1" 'cd javascript/lfb-trade-fe' >/dev/null
herdr pane run "$PANE6_1" 'echo '\''aider --model ollama_chat/qwen2.5-coder:14b --read convention.md --show-diffs --no-auto-commit --chat-mode code --vim .'\''' >/dev/null

# ------------------- window 7: script runner --------------------
tab7_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'script runner' --no-focus)"
TAB7_ID="$(jget '.result.tab.tab_id' "$tab7_json")"
PANE7_1="$(jget '.result.root_pane.pane_id' "$tab7_json")"

name_tab "$TAB7_ID" 'script runner'

herdr pane rename "$PANE7_1" 'script runner' >/dev/null
herdr pane run "$PANE7_1" 'cd python/lhb-trade' >/dev/null
herdr pane run "$PANE7_1" 'source ./env/bin/activate' >/dev/null
herdr pane run "$PANE7_1" 'export PYTHONPATH=$PYTHONPATH:./src' >/dev/null

if [ "$FOCUS_AT_END" = "1" ]; then
  herdr workspace focus "$WS_ID" >/dev/null
fi

# ----------------------------- summary --------------------------------------
echo "==> Done. workspace '$WORKSPACE_LABEL' ($WS_ID):"
herdr workspace list 2>/dev/null \
  | jq -r --arg l "$WORKSPACE_LABEL" \
        '.result.workspaces[] | select(.label==$l)
         | "  workspace \(.workspace_id)  tabs=\(.tab_count)  panes=\(.pane_count)  active=\(.active_tab_id)"'
echo "  tabs:"
herdr tab list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.tabs[]? | "    \(.tab_id)  #\(.number)  \(.label)"' || true
echo "  panes:"
herdr pane list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.panes[]? | "    \(.pane_id)  tab=\(.tab_id)  label=\(.label)  cwd=\(.foreground_cwd)"' || true
