#!/usr/bin/env bash
#
# ob.sh — recreate the tmuxinator `Obsidian` project inside Herdr.
#
# Source of truth: ~/.config/tmuxinator/ob.yml
#   name:  Obsidian
#   root:  ~/Desktop/personal/document/obsidian vault
#   pre_window: export SESSION_HOME="~/.config/nvim/session" ; export VIM_SESSION=$SESSION_HOME/obsidian.vim ; export NEW_VIM_SESSION=$SESSION_HOME/new_obsidian.vim
#   windows: 1 editor(single: editor) | 2 cmd(single: cmd) | 3 mdAnki(even-horizontal: CMD|editor) | 4 new editor(single: new editor) | 5 new cmd(single: new cmd)
#
# Generated by migration-herdr/generate.rb. Re-run the generator with
# FORCE=1 to regenerate from the yml, or edit this file by hand and leave FORCE
# off so the generator will not overwrite it. Run it with:
#     bash ~/.config/tmuxinator/migration-herdr/ob.sh
#
set -euo pipefail

# ----------------------------- configuration --------------------------------
ROOT="${HOME}/Desktop/personal/document/obsidian vault"   # tmuxinator `root:`
WORKSPACE_LABEL='Obsidian'
SPLIT_RATIO="0.7"      # main-* layouts => first pane is larger. If the live
                       # result looks backwards, flip it (or drop --ratio).
FOCUS_AT_END=0         # 1 = focus the new workspace when done; 0 = leave focus
TAB_INDEX_PREFIX=1     # 1 = label tabs "<n> <name>"; 0 = bare names

# ----------------------------- preconditions -------------------------------
command -v herdr >/dev/null 2>&1 || { echo "error: 'herdr' not found in PATH" >&2; exit 1; }
command -v jq    >/dev/null 2>&1 || { echo "error: 'jq' not found in PATH"    >&2; exit 1; }
[ -d "$ROOT" ] || { echo "error: root dir not found: $ROOT" >&2; exit 1; }
# plan: what the yml asks for, and anything obviously unavailable here.
plan() { printf "%s\n" "$*"; }
for d in '/Users/lotp/Desktop/personal/document/obsidian vault'; do
  [ -d "$d" ] || plan "warn: missing dir in yml: $d";
done
for c in 'mdanki'; do
  command -v "$c" >/dev/null 2>&1 || plan "warn: command not on PATH: $c";
done

# extract a jq path from a JSON string  ->  jget '<jq path>' '<json>'
jget() { printf '%s' "$2" | jq -r "$1"; }

# name a tab in creation order, optionally with an index prefix
TAB_INDEX=0
name_tab() { # name_tab '<tab_id>' '<name>'
  TAB_INDEX=$((TAB_INDEX + 1))
  local label="$2"
  if [ "$TAB_INDEX_PREFIX" = "1" ]; then label="$TAB_INDEX $label"; fi
  herdr tab rename "$1" "$label" >/dev/null
  printf '%s\n' "$label"
}

# guard: don't stack a second workspace with this label (tmuxinator refuses to
# restart a project that is already running).
existing="$(herdr workspace list 2>/dev/null | jq -r --arg l "$WORKSPACE_LABEL" '.result.workspaces[]? | select(.label==$l) | .workspace_id' || true)"
if [ -n "$existing" ]; then
  echo "error: workspace '$WORKSPACE_LABEL' already exists ($existing)." >&2
  echo "       close it (herdr workspace close $existing) or change WORKSPACE_LABEL, then re-run." >&2
  exit 1
fi

echo "==> Creating workspace '$WORKSPACE_LABEL' at $ROOT"

# ------------------- window 1: editor --------------------
ws_json="$(herdr workspace create --cwd "$ROOT" --label "$WORKSPACE_LABEL" --no-focus)"
WS_ID="$(jget '.result.workspace.workspace_id' "$ws_json")"
TAB1_ID="$(jget '.result.tab.tab_id' "$ws_json")"
PANE1_1="$(jget '.result.root_pane.pane_id' "$ws_json")"

name_tab "$TAB1_ID" 'editor'

herdr pane rename "$PANE1_1" 'editor' >/dev/null
herdr pane run "$PANE1_1" 'export SESSION_HOME="~/.config/nvim/session"' >/dev/null
herdr pane run "$PANE1_1" 'export VIM_SESSION=$SESSION_HOME/obsidian.vim' >/dev/null
herdr pane run "$PANE1_1" 'export NEW_VIM_SESSION=$SESSION_HOME/new_obsidian.vim' >/dev/null
herdr pane run "$PANE1_1" 'vim -S $VIM_SESSION' >/dev/null

# ------------------- window 2: cmd --------------------
tab2_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'cmd' --no-focus)"
TAB2_ID="$(jget '.result.tab.tab_id' "$tab2_json")"
PANE2_1="$(jget '.result.root_pane.pane_id' "$tab2_json")"

name_tab "$TAB2_ID" 'cmd'

herdr pane rename "$PANE2_1" 'cmd' >/dev/null
herdr pane run "$PANE2_1" 'export SESSION_HOME="~/.config/nvim/session"' >/dev/null
herdr pane run "$PANE2_1" 'export VIM_SESSION=$SESSION_HOME/obsidian.vim' >/dev/null
herdr pane run "$PANE2_1" 'export NEW_VIM_SESSION=$SESSION_HOME/new_obsidian.vim' >/dev/null
herdr pane run "$PANE2_1" 'ls' >/dev/null

# ------------------- window 3: mdAnki --------------------
tab3_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'mdAnki' --no-focus)"
TAB3_ID="$(jget '.result.tab.tab_id' "$tab3_json")"
PANE3_1="$(jget '.result.root_pane.pane_id' "$tab3_json")"

name_tab "$TAB3_ID" 'mdAnki'

herdr pane rename "$PANE3_1" 'CMD' >/dev/null
herdr pane run "$PANE3_1" 'export SESSION_HOME="~/.config/nvim/session"' >/dev/null
herdr pane run "$PANE3_1" 'export VIM_SESSION=$SESSION_HOME/obsidian.vim' >/dev/null
herdr pane run "$PANE3_1" 'export NEW_VIM_SESSION=$SESSION_HOME/new_obsidian.vim' >/dev/null
herdr pane run "$PANE3_1" 'mdanki /tmp/k.md /tmp/tmp.apkg --deck new' >/dev/null

pane3_2_json="$(herdr pane split "$PANE3_1" --direction right --cwd "$ROOT" --no-focus)"
PANE3_2="$(jget '.result.pane.pane_id' "$pane3_2_json")"

herdr pane rename "$PANE3_2" 'editor' >/dev/null
herdr pane run "$PANE3_2" 'export SESSION_HOME="~/.config/nvim/session"' >/dev/null
herdr pane run "$PANE3_2" 'export VIM_SESSION=$SESSION_HOME/obsidian.vim' >/dev/null
herdr pane run "$PANE3_2" 'export NEW_VIM_SESSION=$SESSION_HOME/new_obsidian.vim' >/dev/null
herdr pane run "$PANE3_2" 'vim /tmp/k.md' >/dev/null

# ------------------- window 4: new editor --------------------
tab4_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'new editor' --no-focus)"
TAB4_ID="$(jget '.result.tab.tab_id' "$tab4_json")"
PANE4_1="$(jget '.result.root_pane.pane_id' "$tab4_json")"

name_tab "$TAB4_ID" 'new editor'

herdr pane rename "$PANE4_1" 'new editor' >/dev/null
herdr pane run "$PANE4_1" 'export SESSION_HOME="~/.config/nvim/session"' >/dev/null
herdr pane run "$PANE4_1" 'export VIM_SESSION=$SESSION_HOME/obsidian.vim' >/dev/null
herdr pane run "$PANE4_1" 'export NEW_VIM_SESSION=$SESSION_HOME/new_obsidian.vim' >/dev/null
herdr pane run "$PANE4_1" 'cd ../kkk' >/dev/null
herdr pane run "$PANE4_1" 'vim -S $NEW_VIM_SESSION' >/dev/null

# ------------------- window 5: new cmd --------------------
tab5_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'new cmd' --no-focus)"
TAB5_ID="$(jget '.result.tab.tab_id' "$tab5_json")"
PANE5_1="$(jget '.result.root_pane.pane_id' "$tab5_json")"

name_tab "$TAB5_ID" 'new cmd'

herdr pane rename "$PANE5_1" 'new cmd' >/dev/null
herdr pane run "$PANE5_1" 'export SESSION_HOME="~/.config/nvim/session"' >/dev/null
herdr pane run "$PANE5_1" 'export VIM_SESSION=$SESSION_HOME/obsidian.vim' >/dev/null
herdr pane run "$PANE5_1" 'export NEW_VIM_SESSION=$SESSION_HOME/new_obsidian.vim' >/dev/null
herdr pane run "$PANE5_1" 'cd ../kkk' >/dev/null
herdr pane run "$PANE5_1" 'ls' >/dev/null

if [ "$FOCUS_AT_END" = "1" ]; then
  herdr workspace focus "$WS_ID" >/dev/null
fi

# ----------------------------- summary --------------------------------------
echo "==> Done. workspace '$WORKSPACE_LABEL' ($WS_ID):"
herdr workspace list 2>/dev/null \
  | jq -r --arg l "$WORKSPACE_LABEL" \
        '.result.workspaces[] | select(.label==$l)
         | "  workspace \(.workspace_id)  tabs=\(.tab_count)  panes=\(.pane_count)  active=\(.active_tab_id)"'
echo "  tabs:"
herdr tab list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.tabs[]? | "    \(.tab_id)  #\(.number)  \(.label)"' || true
echo "  panes:"
herdr pane list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.panes[]? | "    \(.pane_id)  tab=\(.tab_id)  label=\(.label)  cwd=\(.foreground_cwd)"' || true
