#!/usr/bin/env bash
#
# singleorigin-general.sh — recreate the tmuxinator `Single Origin General` project inside Herdr.
#
# Source of truth: ~/.config/tmuxinator/singleorigin-general.yml
#   name:  Single Origin General
#   root:  ~/Desktop/Single-Origin/code
#   pre_window: export SESSION_HOME="~/.config/nvim/session/single-origin"
#   windows: 1 Proto Editor(single: Proto Editor) | 2 Proto CMD(main-vertical: cmd 0|cmd 1) | 3 Helm Editor(single: Helm Editor) | 4 Helm CMD(single: Helm CMD) | 5 Terraform Editor(single: Terraform Editor) | 6 Terraform CMD(main-vertical: cmd 0|cmd 1) | 7 Airflow Editor(single: Airflow Editor) | 8 Airflow CMD(main-vertical: cmd 0|cmd 1) | 9 Bootstrap Editor(single: Bootstrap Editor) | 10 Bootstrap CMD(single: Bootstrap CMD)
#
# Generated by migration-herdr/generate.rb. Re-run the generator with
# FORCE=1 to regenerate from the yml, or edit this file by hand and leave FORCE
# off so the generator will not overwrite it. Run it with:
#     bash ~/.config/tmuxinator/migration-herdr/singleorigin-general.sh
#
set -euo pipefail

# ----------------------------- configuration --------------------------------
ROOT="${HOME}/Desktop/Single-Origin/code"   # tmuxinator `root:`
WORKSPACE_LABEL='Single Origin General'
SPLIT_RATIO="0.7"      # main-* layouts => first pane is larger. If the live
                       # result looks backwards, flip it (or drop --ratio).
FOCUS_AT_END=0         # 1 = focus the new workspace when done; 0 = leave focus
TAB_INDEX_PREFIX=1     # 1 = label tabs "<n> <name>"; 0 = bare names

# ----------------------------- preconditions -------------------------------
command -v herdr >/dev/null 2>&1 || { echo "error: 'herdr' not found in PATH" >&2; exit 1; }
command -v jq    >/dev/null 2>&1 || { echo "error: 'jq' not found in PATH"    >&2; exit 1; }
[ -d "$ROOT" ] || { echo "error: root dir not found: $ROOT" >&2; exit 1; }
# plan: what the yml asks for, and anything obviously unavailable here.
plan() { printf "%s\n" "$*"; }
for d in '/Users/lotp/Desktop/Single-Origin/code'; do
  [ -d "$d" ] || plan "warn: missing dir in yml: $d";
done
for c in 'scripts/generate_openapi.py' 'buf'; do
  command -v "$c" >/dev/null 2>&1 || plan "warn: command not on PATH: $c";
done

# extract a jq path from a JSON string  ->  jget '<jq path>' '<json>'
jget() { printf '%s' "$2" | jq -r "$1"; }

# name a tab in creation order, optionally with an index prefix
TAB_INDEX=0
name_tab() { # name_tab '<tab_id>' '<name>'
  TAB_INDEX=$((TAB_INDEX + 1))
  local label="$2"
  if [ "$TAB_INDEX_PREFIX" = "1" ]; then label="$TAB_INDEX $label"; fi
  herdr tab rename "$1" "$label" >/dev/null
  printf '%s\n' "$label"
}

# guard: don't stack a second workspace with this label (tmuxinator refuses to
# restart a project that is already running).
existing="$(herdr workspace list 2>/dev/null | jq -r --arg l "$WORKSPACE_LABEL" '.result.workspaces[]? | select(.label==$l) | .workspace_id' || true)"
if [ -n "$existing" ]; then
  echo "error: workspace '$WORKSPACE_LABEL' already exists ($existing)." >&2
  echo "       close it (herdr workspace close $existing) or change WORKSPACE_LABEL, then re-run." >&2
  exit 1
fi

echo "==> Creating workspace '$WORKSPACE_LABEL' at $ROOT"

# ------------------- window 1: Proto Editor --------------------
ws_json="$(herdr workspace create --cwd "$ROOT" --label "$WORKSPACE_LABEL" --no-focus)"
WS_ID="$(jget '.result.workspace.workspace_id' "$ws_json")"
TAB1_ID="$(jget '.result.tab.tab_id' "$ws_json")"
PANE1_1="$(jget '.result.root_pane.pane_id' "$ws_json")"

name_tab "$TAB1_ID" 'Proto Editor'

herdr pane rename "$PANE1_1" 'Proto Editor' >/dev/null
herdr pane run "$PANE1_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE1_1" 'cd proto' >/dev/null
herdr pane run "$PANE1_1" 'export VIM_SESSION=$SESSION_HOME/proto.vim' >/dev/null

# ------------------- window 2: Proto CMD --------------------
tab2_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'Proto CMD' --no-focus)"
TAB2_ID="$(jget '.result.tab.tab_id' "$tab2_json")"
PANE2_1="$(jget '.result.root_pane.pane_id' "$tab2_json")"

name_tab "$TAB2_ID" 'Proto CMD'

herdr pane rename "$PANE2_1" 'cmd 0' >/dev/null
herdr pane run "$PANE2_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE2_1" 'cd proto' >/dev/null
herdr pane run "$PANE2_1" 'git status' >/dev/null
herdr pane run "$PANE2_1" 'export GOPATH=$HOME/go' >/dev/null
herdr pane run "$PANE2_1" 'export PATH=$PATH:$GOPATH/bin' >/dev/null
herdr pane run "$PANE2_1" 'source .venv/bin/activate' >/dev/null
herdr pane run "$PANE2_1" 'scripts/generate_openapi.py singleorigin-api' >/dev/null

pane2_2_json="$(herdr pane split "$PANE2_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE2_2="$(jget '.result.pane.pane_id' "$pane2_2_json")"

herdr pane rename "$PANE2_2" 'cmd 1' >/dev/null
herdr pane run "$PANE2_2" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE2_2" 'cd proto/singleorigin-api' >/dev/null
herdr pane run "$PANE2_2" 'buf lint' >/dev/null

# ------------------- window 3: Helm Editor --------------------
tab3_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'Helm Editor' --no-focus)"
TAB3_ID="$(jget '.result.tab.tab_id' "$tab3_json")"
PANE3_1="$(jget '.result.root_pane.pane_id' "$tab3_json")"

name_tab "$TAB3_ID" 'Helm Editor'

herdr pane rename "$PANE3_1" 'Helm Editor' >/dev/null
herdr pane run "$PANE3_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE3_1" 'cd helm' >/dev/null
herdr pane run "$PANE3_1" 'export VIM_SESSION=$SESSION_HOME/helm.vim' >/dev/null

# ------------------- window 4: Helm CMD --------------------
tab4_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'Helm CMD' --no-focus)"
TAB4_ID="$(jget '.result.tab.tab_id' "$tab4_json")"
PANE4_1="$(jget '.result.root_pane.pane_id' "$tab4_json")"

name_tab "$TAB4_ID" 'Helm CMD'

herdr pane rename "$PANE4_1" 'Helm CMD' >/dev/null
herdr pane run "$PANE4_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE4_1" 'cd helm' >/dev/null
herdr pane run "$PANE4_1" 'git status' >/dev/null

# ------------------- window 5: Terraform Editor --------------------
tab5_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'Terraform Editor' --no-focus)"
TAB5_ID="$(jget '.result.tab.tab_id' "$tab5_json")"
PANE5_1="$(jget '.result.root_pane.pane_id' "$tab5_json")"

name_tab "$TAB5_ID" 'Terraform Editor'

herdr pane rename "$PANE5_1" 'Terraform Editor' >/dev/null
herdr pane run "$PANE5_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE5_1" 'cd terraform' >/dev/null
herdr pane run "$PANE5_1" 'export VIM_SESSION=$SESSION_HOME/terraform.vim' >/dev/null

# ------------------- window 6: Terraform CMD --------------------
tab6_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'Terraform CMD' --no-focus)"
TAB6_ID="$(jget '.result.tab.tab_id' "$tab6_json")"
PANE6_1="$(jget '.result.root_pane.pane_id' "$tab6_json")"

name_tab "$TAB6_ID" 'Terraform CMD'

herdr pane rename "$PANE6_1" 'cmd 0' >/dev/null
herdr pane run "$PANE6_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE6_1" 'cd terraform' >/dev/null
herdr pane run "$PANE6_1" 'git status' >/dev/null

pane6_2_json="$(herdr pane split "$PANE6_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE6_2="$(jget '.result.pane.pane_id' "$pane6_2_json")"

herdr pane rename "$PANE6_2" 'cmd 1' >/dev/null
herdr pane run "$PANE6_2" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE6_2" 'cd terraform' >/dev/null

# ------------------- window 7: Airflow Editor --------------------
tab7_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'Airflow Editor' --no-focus)"
TAB7_ID="$(jget '.result.tab.tab_id' "$tab7_json")"
PANE7_1="$(jget '.result.root_pane.pane_id' "$tab7_json")"

name_tab "$TAB7_ID" 'Airflow Editor'

herdr pane rename "$PANE7_1" 'Airflow Editor' >/dev/null
herdr pane run "$PANE7_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE7_1" 'cd airflow-dag' >/dev/null
herdr pane run "$PANE7_1" 'export VIM_SESSION=$SESSION_HOME/airflow.vim' >/dev/null

# ------------------- window 8: Airflow CMD --------------------
tab8_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'Airflow CMD' --no-focus)"
TAB8_ID="$(jget '.result.tab.tab_id' "$tab8_json")"
PANE8_1="$(jget '.result.root_pane.pane_id' "$tab8_json")"

name_tab "$TAB8_ID" 'Airflow CMD'

herdr pane rename "$PANE8_1" 'cmd 0' >/dev/null
herdr pane run "$PANE8_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE8_1" 'cd airflow-dag' >/dev/null
herdr pane run "$PANE8_1" 'git status' >/dev/null

pane8_2_json="$(herdr pane split "$PANE8_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE8_2="$(jget '.result.pane.pane_id' "$pane8_2_json")"

herdr pane rename "$PANE8_2" 'cmd 1' >/dev/null
herdr pane run "$PANE8_2" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE8_2" 'cd airflow-dag' >/dev/null

# ------------------- window 9: Bootstrap Editor --------------------
tab9_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'Bootstrap Editor' --no-focus)"
TAB9_ID="$(jget '.result.tab.tab_id' "$tab9_json")"
PANE9_1="$(jget '.result.root_pane.pane_id' "$tab9_json")"

name_tab "$TAB9_ID" 'Bootstrap Editor'

herdr pane rename "$PANE9_1" 'Bootstrap Editor' >/dev/null
herdr pane run "$PANE9_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE9_1" 'cd tenant-bootstrap' >/dev/null
herdr pane run "$PANE9_1" 'export VIM_SESSION=$SESSION_HOME/tenantBootstrap.vim' >/dev/null

# ------------------- window 10: Bootstrap CMD --------------------
tab10_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'Bootstrap CMD' --no-focus)"
TAB10_ID="$(jget '.result.tab.tab_id' "$tab10_json")"
PANE10_1="$(jget '.result.root_pane.pane_id' "$tab10_json")"

name_tab "$TAB10_ID" 'Bootstrap CMD'

herdr pane rename "$PANE10_1" 'Bootstrap CMD' >/dev/null
herdr pane run "$PANE10_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null

if [ "$FOCUS_AT_END" = "1" ]; then
  herdr workspace focus "$WS_ID" >/dev/null
fi

# ----------------------------- summary --------------------------------------
echo "==> Done. workspace '$WORKSPACE_LABEL' ($WS_ID):"
herdr workspace list 2>/dev/null \
  | jq -r --arg l "$WORKSPACE_LABEL" \
        '.result.workspaces[] | select(.label==$l)
         | "  workspace \(.workspace_id)  tabs=\(.tab_count)  panes=\(.pane_count)  active=\(.active_tab_id)"'
echo "  tabs:"
herdr tab list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.tabs[]? | "    \(.tab_id)  #\(.number)  \(.label)"' || true
echo "  panes:"
herdr pane list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.panes[]? | "    \(.pane_id)  tab=\(.tab_id)  label=\(.label)  cwd=\(.foreground_cwd)"' || true
