#!/usr/bin/env bash
#
# singleorigin-be.sh — recreate the tmuxinator `Single Origin BE` project inside Herdr.
#
# Source of truth: ~/.config/tmuxinator/singleorigin-be.yml
#   name:  Single Origin BE
#   root:  ~/Desktop/Single-Origin/code/singleorigin-api
#   pre_window: export JAVA_HOME=~/.config/java/jdk-17.0.6.jdk/Contents/Home/ ; export PATH=%JAVA_HOME/bin:$PATH ; export SESSION_HOME="~/.config/nvim/session/single-origin" ; export DOCKER_BUILDKIT=0 ; export COMPOSE_PROFILES=infra,core
#   windows: 1 Core Editor(single: Core Editor) | 2 API CMD(single: API CMD) | 3 API-Runner(single: API-Runner) | 4 Docker(main-vertical: cmd|runner) | 5 db(main-vertical: cmd 1|cmd 2) | 6 DB Playground(main-vertical: cmd|edit) | 7 API Editor(single: API Editor)
#
# Generated by migration-herdr/generate.rb. Re-run the generator with
# FORCE=1 to regenerate from the yml, or edit this file by hand and leave FORCE
# off so the generator will not overwrite it. Run it with:
#     bash ~/.config/tmuxinator/migration-herdr/singleorigin-be.sh
#
set -euo pipefail

# ----------------------------- configuration --------------------------------
ROOT="${HOME}/Desktop/Single-Origin/code/singleorigin-api"   # tmuxinator `root:`
WORKSPACE_LABEL='Single Origin BE'
SPLIT_RATIO="0.7"      # main-* layouts => first pane is larger. If the live
                       # result looks backwards, flip it (or drop --ratio).
FOCUS_AT_END=0         # 1 = focus the new workspace when done; 0 = leave focus
TAB_INDEX_PREFIX=1     # 1 = label tabs "<n> <name>"; 0 = bare names

# ----------------------------- preconditions -------------------------------
command -v herdr >/dev/null 2>&1 || { echo "error: 'herdr' not found in PATH" >&2; exit 1; }
command -v jq    >/dev/null 2>&1 || { echo "error: 'jq' not found in PATH"    >&2; exit 1; }
[ -d "$ROOT" ] || { echo "error: root dir not found: $ROOT" >&2; exit 1; }
# plan: what the yml asks for, and anything obviously unavailable here.
plan() { printf "%s\n" "$*"; }
for d in '/Users/lotp/Desktop/Single-Origin/code/singleorigin-api'; do
  [ -d "$d" ] || plan "warn: missing dir in yml: $d";
done
for c in 'docker-compose'; do
  command -v "$c" >/dev/null 2>&1 || plan "warn: command not on PATH: $c";
done

# extract a jq path from a JSON string  ->  jget '<jq path>' '<json>'
jget() { printf '%s' "$2" | jq -r "$1"; }

# name a tab in creation order, optionally with an index prefix
TAB_INDEX=0
name_tab() { # name_tab '<tab_id>' '<name>'
  TAB_INDEX=$((TAB_INDEX + 1))
  local label="$2"
  if [ "$TAB_INDEX_PREFIX" = "1" ]; then label="$TAB_INDEX $label"; fi
  herdr tab rename "$1" "$label" >/dev/null
  printf '%s\n' "$label"
}

# guard: don't stack a second workspace with this label (tmuxinator refuses to
# restart a project that is already running).
existing="$(herdr workspace list 2>/dev/null | jq -r --arg l "$WORKSPACE_LABEL" '.result.workspaces[]? | select(.label==$l) | .workspace_id' || true)"
if [ -n "$existing" ]; then
  echo "error: workspace '$WORKSPACE_LABEL' already exists ($existing)." >&2
  echo "       close it (herdr workspace close $existing) or change WORKSPACE_LABEL, then re-run." >&2
  exit 1
fi

echo "==> Creating workspace '$WORKSPACE_LABEL' at $ROOT"

# ------------------- window 1: Core Editor --------------------
ws_json="$(herdr workspace create --cwd "$ROOT" --label "$WORKSPACE_LABEL" --no-focus)"
WS_ID="$(jget '.result.workspace.workspace_id' "$ws_json")"
TAB1_ID="$(jget '.result.tab.tab_id' "$ws_json")"
PANE1_1="$(jget '.result.root_pane.pane_id' "$ws_json")"

name_tab "$TAB1_ID" 'Core Editor'

herdr pane rename "$PANE1_1" 'Core Editor' >/dev/null
herdr pane run "$PANE1_1" 'export JAVA_HOME=~/.config/java/jdk-17.0.6.jdk/Contents/Home/' >/dev/null
herdr pane run "$PANE1_1" 'export PATH=%JAVA_HOME/bin:$PATH' >/dev/null
herdr pane run "$PANE1_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE1_1" 'export DOCKER_BUILDKIT=0' >/dev/null
herdr pane run "$PANE1_1" 'export COMPOSE_PROFILES=infra,core' >/dev/null
herdr pane run "$PANE1_1" 'cd core' >/dev/null
herdr pane run "$PANE1_1" 'export VIM_SESSION=$SESSION_HOME/api-core.vim' >/dev/null

# ------------------- window 2: API CMD --------------------
tab2_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'API CMD' --no-focus)"
TAB2_ID="$(jget '.result.tab.tab_id' "$tab2_json")"
PANE2_1="$(jget '.result.root_pane.pane_id' "$tab2_json")"

name_tab "$TAB2_ID" 'API CMD'

herdr pane rename "$PANE2_1" 'API CMD' >/dev/null
herdr pane run "$PANE2_1" 'export JAVA_HOME=~/.config/java/jdk-17.0.6.jdk/Contents/Home/' >/dev/null
herdr pane run "$PANE2_1" 'export PATH=%JAVA_HOME/bin:$PATH' >/dev/null
herdr pane run "$PANE2_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE2_1" 'export DOCKER_BUILDKIT=0' >/dev/null
herdr pane run "$PANE2_1" 'export COMPOSE_PROFILES=infra,core' >/dev/null
herdr pane run "$PANE2_1" 'git status' >/dev/null

# ------------------- window 3: API-Runner --------------------
tab3_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'API-Runner' --no-focus)"
TAB3_ID="$(jget '.result.tab.tab_id' "$tab3_json")"
PANE3_1="$(jget '.result.root_pane.pane_id' "$tab3_json")"

name_tab "$TAB3_ID" 'API-Runner'

herdr pane rename "$PANE3_1" 'API-Runner' >/dev/null
herdr pane run "$PANE3_1" 'export JAVA_HOME=~/.config/java/jdk-17.0.6.jdk/Contents/Home/' >/dev/null
herdr pane run "$PANE3_1" 'export PATH=%JAVA_HOME/bin:$PATH' >/dev/null
herdr pane run "$PANE3_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE3_1" 'export DOCKER_BUILDKIT=0' >/dev/null
herdr pane run "$PANE3_1" 'export COMPOSE_PROFILES=infra,core' >/dev/null
herdr pane run "$PANE3_1" 'sleep 40' >/dev/null
herdr pane run "$PANE3_1" 'echo '\''java --add-opens java.base/java.nio=ALL-UNNAMED -jar ./core/build/libs/core-1.0-SNAPSHOT.jar'\''' >/dev/null

# ------------------- window 4: Docker --------------------
tab4_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'Docker' --no-focus)"
TAB4_ID="$(jget '.result.tab.tab_id' "$tab4_json")"
PANE4_1="$(jget '.result.root_pane.pane_id' "$tab4_json")"

name_tab "$TAB4_ID" 'Docker'

herdr pane rename "$PANE4_1" 'cmd' >/dev/null
herdr pane run "$PANE4_1" 'export JAVA_HOME=~/.config/java/jdk-17.0.6.jdk/Contents/Home/' >/dev/null
herdr pane run "$PANE4_1" 'export PATH=%JAVA_HOME/bin:$PATH' >/dev/null
herdr pane run "$PANE4_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE4_1" 'export DOCKER_BUILDKIT=0' >/dev/null
herdr pane run "$PANE4_1" 'export COMPOSE_PROFILES=infra,core' >/dev/null
herdr pane run "$PANE4_1" 'cd dev' >/dev/null
herdr pane run "$PANE4_1" 'echo '\''docker-compose build'\''' >/dev/null
herdr pane run "$PANE4_1" 'echo '\''docker-compose up'\''' >/dev/null

pane4_2_json="$(herdr pane split "$PANE4_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE4_2="$(jget '.result.pane.pane_id' "$pane4_2_json")"

herdr pane rename "$PANE4_2" 'runner' >/dev/null
herdr pane run "$PANE4_2" 'export JAVA_HOME=~/.config/java/jdk-17.0.6.jdk/Contents/Home/' >/dev/null
herdr pane run "$PANE4_2" 'export PATH=%JAVA_HOME/bin:$PATH' >/dev/null
herdr pane run "$PANE4_2" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE4_2" 'export DOCKER_BUILDKIT=0' >/dev/null
herdr pane run "$PANE4_2" 'export COMPOSE_PROFILES=infra,core' >/dev/null
herdr pane run "$PANE4_2" 'cd dev' >/dev/null
herdr pane run "$PANE4_2" 'docker-compose help' >/dev/null

# ------------------- window 5: db --------------------
tab5_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'db' --no-focus)"
TAB5_ID="$(jget '.result.tab.tab_id' "$tab5_json")"
PANE5_1="$(jget '.result.root_pane.pane_id' "$tab5_json")"

name_tab "$TAB5_ID" 'db'

herdr pane rename "$PANE5_1" 'cmd 1' >/dev/null
herdr pane run "$PANE5_1" 'export JAVA_HOME=~/.config/java/jdk-17.0.6.jdk/Contents/Home/' >/dev/null
herdr pane run "$PANE5_1" 'export PATH=%JAVA_HOME/bin:$PATH' >/dev/null
herdr pane run "$PANE5_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE5_1" 'export DOCKER_BUILDKIT=0' >/dev/null
herdr pane run "$PANE5_1" 'export COMPOSE_PROFILES=infra,core' >/dev/null
herdr pane run "$PANE5_1" 'cd ..' >/dev/null
herdr pane run "$PANE5_1" '$(readlink -f $(which postgres)) -D db' >/dev/null

pane5_2_json="$(herdr pane split "$PANE5_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE5_2="$(jget '.result.pane.pane_id' "$pane5_2_json")"

herdr pane rename "$PANE5_2" 'cmd 2' >/dev/null
herdr pane run "$PANE5_2" 'export JAVA_HOME=~/.config/java/jdk-17.0.6.jdk/Contents/Home/' >/dev/null
herdr pane run "$PANE5_2" 'export PATH=%JAVA_HOME/bin:$PATH' >/dev/null
herdr pane run "$PANE5_2" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE5_2" 'export DOCKER_BUILDKIT=0' >/dev/null
herdr pane run "$PANE5_2" 'export COMPOSE_PROFILES=infra,core' >/dev/null
herdr pane run "$PANE5_2" 'cd ..' >/dev/null
herdr pane run "$PANE5_2" 'echo '\''$(readlink -f $(which pg_ctl)) -D db stop'\''' >/dev/null

# ------------------- window 6: DB Playground --------------------
tab6_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'DB Playground' --no-focus)"
TAB6_ID="$(jget '.result.tab.tab_id' "$tab6_json")"
PANE6_1="$(jget '.result.root_pane.pane_id' "$tab6_json")"

name_tab "$TAB6_ID" 'DB Playground'

herdr pane rename "$PANE6_1" 'cmd' >/dev/null
herdr pane run "$PANE6_1" 'export JAVA_HOME=~/.config/java/jdk-17.0.6.jdk/Contents/Home/' >/dev/null
herdr pane run "$PANE6_1" 'export PATH=%JAVA_HOME/bin:$PATH' >/dev/null
herdr pane run "$PANE6_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE6_1" 'export DOCKER_BUILDKIT=0' >/dev/null
herdr pane run "$PANE6_1" 'export COMPOSE_PROFILES=infra,core' >/dev/null
herdr pane run "$PANE6_1" 'cd ../guide' >/dev/null
herdr pane run "$PANE6_1" 'cat sqlCommand | psql postgresql://postgres:postgres@localhost:5432 -f -' >/dev/null

pane6_2_json="$(herdr pane split "$PANE6_1" --direction right --ratio "$SPLIT_RATIO" --cwd "$ROOT" --no-focus)"
PANE6_2="$(jget '.result.pane.pane_id' "$pane6_2_json")"

herdr pane rename "$PANE6_2" 'edit' >/dev/null
herdr pane run "$PANE6_2" 'export JAVA_HOME=~/.config/java/jdk-17.0.6.jdk/Contents/Home/' >/dev/null
herdr pane run "$PANE6_2" 'export PATH=%JAVA_HOME/bin:$PATH' >/dev/null
herdr pane run "$PANE6_2" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE6_2" 'export DOCKER_BUILDKIT=0' >/dev/null
herdr pane run "$PANE6_2" 'export COMPOSE_PROFILES=infra,core' >/dev/null
herdr pane run "$PANE6_2" 'cd ../guide' >/dev/null
herdr pane run "$PANE6_2" 'vim sqlCommand' >/dev/null

# ------------------- window 7: API Editor --------------------
tab7_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'API Editor' --no-focus)"
TAB7_ID="$(jget '.result.tab.tab_id' "$tab7_json")"
PANE7_1="$(jget '.result.root_pane.pane_id' "$tab7_json")"

name_tab "$TAB7_ID" 'API Editor'

herdr pane rename "$PANE7_1" 'API Editor' >/dev/null
herdr pane run "$PANE7_1" 'export JAVA_HOME=~/.config/java/jdk-17.0.6.jdk/Contents/Home/' >/dev/null
herdr pane run "$PANE7_1" 'export PATH=%JAVA_HOME/bin:$PATH' >/dev/null
herdr pane run "$PANE7_1" 'export SESSION_HOME="~/.config/nvim/session/single-origin"' >/dev/null
herdr pane run "$PANE7_1" 'export DOCKER_BUILDKIT=0' >/dev/null
herdr pane run "$PANE7_1" 'export COMPOSE_PROFILES=infra,core' >/dev/null
herdr pane run "$PANE7_1" 'export VIM_SESSION=$SESSION_HOME/api.vim' >/dev/null

if [ "$FOCUS_AT_END" = "1" ]; then
  herdr workspace focus "$WS_ID" >/dev/null
fi

# ----------------------------- summary --------------------------------------
echo "==> Done. workspace '$WORKSPACE_LABEL' ($WS_ID):"
herdr workspace list 2>/dev/null \
  | jq -r --arg l "$WORKSPACE_LABEL" \
        '.result.workspaces[] | select(.label==$l)
         | "  workspace \(.workspace_id)  tabs=\(.tab_count)  panes=\(.pane_count)  active=\(.active_tab_id)"'
echo "  tabs:"
herdr tab list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.tabs[]? | "    \(.tab_id)  #\(.number)  \(.label)"' || true
echo "  panes:"
herdr pane list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.panes[]? | "    \(.pane_id)  tab=\(.tab_id)  label=\(.label)  cwd=\(.foreground_cwd)"' || true
