#!/usr/bin/env bash
#
# video-making.sh — recreate the tmuxinator `video-making` project inside Herdr.
#
# Source of truth: ~/.config/tmuxinator/video-making.yml
#   name:  video-making
#   root:  ~/Desktop/personal/videos
#   windows: 1 Kokoro TTS(single: Kokoro TTS) | 2 BBDown(single: BBDown) | 3 Extract Text(single: Extract Text)
#
# Generated by migration-herdr/generate.rb. Re-run the generator with
# FORCE=1 to regenerate from the yml, or edit this file by hand and leave FORCE
# off so the generator will not overwrite it. Run it with:
#     bash ~/.config/tmuxinator/migration-herdr/video-making.sh
#
set -euo pipefail

# ----------------------------- configuration --------------------------------
ROOT="${HOME}/Desktop/personal/videos"   # tmuxinator `root:`
WORKSPACE_LABEL='video-making'
SPLIT_RATIO="0.7"      # main-* layouts => first pane is larger. If the live
                       # result looks backwards, flip it (or drop --ratio).
FOCUS_AT_END=0         # 1 = focus the new workspace when done; 0 = leave focus
TAB_INDEX_PREFIX=1     # 1 = label tabs "<n> <name>"; 0 = bare names

# ----------------------------- preconditions -------------------------------
command -v herdr >/dev/null 2>&1 || { echo "error: 'herdr' not found in PATH" >&2; exit 1; }
command -v jq    >/dev/null 2>&1 || { echo "error: 'jq' not found in PATH"    >&2; exit 1; }
[ -d "$ROOT" ] || { echo "error: root dir not found: $ROOT" >&2; exit 1; }
# plan: what the yml asks for, and anything obviously unavailable here.
plan() { printf "%s\n" "$*"; }
for d in '/Users/lotp/Desktop/personal/videos'; do
  [ -d "$d" ] || plan "warn: missing dir in yml: $d";
done
for c in 'python3.11'; do
  command -v "$c" >/dev/null 2>&1 || plan "warn: command not on PATH: $c";
done

# extract a jq path from a JSON string  ->  jget '<jq path>' '<json>'
jget() { printf '%s' "$2" | jq -r "$1"; }

# name a tab in creation order, optionally with an index prefix
TAB_INDEX=0
name_tab() { # name_tab '<tab_id>' '<name>'
  TAB_INDEX=$((TAB_INDEX + 1))
  local label="$2"
  if [ "$TAB_INDEX_PREFIX" = "1" ]; then label="$TAB_INDEX $label"; fi
  herdr tab rename "$1" "$label" >/dev/null
  printf '%s\n' "$label"
}

# guard: don't stack a second workspace with this label (tmuxinator refuses to
# restart a project that is already running).
existing="$(herdr workspace list 2>/dev/null | jq -r --arg l "$WORKSPACE_LABEL" '.result.workspaces[]? | select(.label==$l) | .workspace_id' || true)"
if [ -n "$existing" ]; then
  echo "error: workspace '$WORKSPACE_LABEL' already exists ($existing)." >&2
  echo "       close it (herdr workspace close $existing) or change WORKSPACE_LABEL, then re-run." >&2
  exit 1
fi

echo "==> Creating workspace '$WORKSPACE_LABEL' at $ROOT"

# ------------------- window 1: Kokoro TTS --------------------
ws_json="$(herdr workspace create --cwd "$ROOT" --label "$WORKSPACE_LABEL" --no-focus)"
WS_ID="$(jget '.result.workspace.workspace_id' "$ws_json")"
TAB1_ID="$(jget '.result.tab.tab_id' "$ws_json")"
PANE1_1="$(jget '.result.root_pane.pane_id' "$ws_json")"

name_tab "$TAB1_ID" 'Kokoro TTS'

herdr pane rename "$PANE1_1" 'Kokoro TTS' >/dev/null
herdr pane run "$PANE1_1" 'cd ../project/python/Kokoro-TTS-Local' >/dev/null
herdr pane run "$PANE1_1" 'source venv/bin/activate' >/dev/null
herdr pane run "$PANE1_1" 'echo '\''visit http://localhost:7860'\''' >/dev/null
herdr pane run "$PANE1_1" 'python3.11 gradio_interface.py' >/dev/null

# ------------------- window 2: BBDown --------------------
tab2_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'BBDown' --no-focus)"
TAB2_ID="$(jget '.result.tab.tab_id' "$tab2_json")"
PANE2_1="$(jget '.result.root_pane.pane_id' "$tab2_json")"

name_tab "$TAB2_ID" 'BBDown'

herdr pane rename "$PANE2_1" 'BBDown' >/dev/null
herdr pane run "$PANE2_1" 'echo '\''./BBDown -tv https://www.bilibili.com/video/BV19Ur3YPEi5/\?spm_id_from\=333.1387.collection.video_card.click\&vd_source\=83c1c03a323974c2109616b8b52b79a5 -ia'\''' >/dev/null

# ------------------- window 3: Extract Text --------------------
tab3_json="$(herdr tab create --workspace "$WS_ID" --cwd "$ROOT" --label 'Extract Text' --no-focus)"
TAB3_ID="$(jget '.result.tab.tab_id' "$tab3_json")"
PANE3_1="$(jget '.result.root_pane.pane_id' "$tab3_json")"

name_tab "$TAB3_ID" 'Extract Text'

herdr pane rename "$PANE3_1" 'Extract Text' >/dev/null
herdr pane run "$PANE3_1" 'echo '\''ffmpeg -i test.mp4  -ar 16000 /tmp/test.wav'\''' >/dev/null
herdr pane run "$PANE3_1" 'echo '\''whisper-cpp -otxt -of test.txt -m ggml-large-v3.bin -f test.wav -l auto'\''' >/dev/null

if [ "$FOCUS_AT_END" = "1" ]; then
  herdr workspace focus "$WS_ID" >/dev/null
fi

# ----------------------------- summary --------------------------------------
echo "==> Done. workspace '$WORKSPACE_LABEL' ($WS_ID):"
herdr workspace list 2>/dev/null \
  | jq -r --arg l "$WORKSPACE_LABEL" \
        '.result.workspaces[] | select(.label==$l)
         | "  workspace \(.workspace_id)  tabs=\(.tab_count)  panes=\(.pane_count)  active=\(.active_tab_id)"'
echo "  tabs:"
herdr tab list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.tabs[]? | "    \(.tab_id)  #\(.number)  \(.label)"' || true
echo "  panes:"
herdr pane list --workspace "$WS_ID" 2>/dev/null \
  | jq -r '.result.panes[]? | "    \(.pane_id)  tab=\(.tab_id)  label=\(.label)  cwd=\(.foreground_cwd)"' || true
